### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by yjt123456789** [xahidbuffon/funie-gan#1]
When I am running train_funiegan. py, the program always appears the output of the following figure, and then stays still. How to solve this problem?

![结果](https://user-images.githubusercontent.com/49440770/67351381-f3b6b580-f57f-11e9-95a3-920b96617ed5.png)

**Comment by xahidbuffon** [comment]
If it is a memory allocation problem, maybe try training with a lower batch-size.
