### ISSUE TITLE
UIQM implementation may be wrong.

### ISSUE THREAD

**Issue by Xiaodong-Bran** [xahidbuffon/funie-gan#2]
Hi, I found there may be something wrong with your implementation for UIQM( UIConM). I thought you follow the implementation for [EMEE](https://sci-hub.tw/https://ieeexplore.ieee.org/document/5609219) instead of logAMEE as described in the original paper.

Let me know if I am wrong.

**Comment by xahidbuffon** [comment]
Thanks for letting us know; we will check and get back to you soon.

**Comment by xahidbuffon** [comment]
Hi, the implementation is correct up to scale. Note that the Sec III-C of original paper refers to this paper (both by Panetta et al.) for UIConM formula; following its PLIP operations should reduce to an equivalent calculation.

**Comment by xahidbuffon** [comment]
Hi, the implementation is correct up to scale. Note that the Sec III-C of original paper refers to this paper (both by Panetta et al.) for UIConM formula; following its PLIP operations should reduce to an equivalent calculation. Let me know what you think!
